### PR TITLE
Rename packages

### PR DESCRIPTION
**Pull request by nwmartin**
Renamed all of the softartisans packages to ripariandata instead.

### CODE REVIEW

**Comment by ScottDugas** [comment]
The pom.xml and example urls need to be updated, I think that should be it, but a search for softartisans shouldn't return anything. You can either use hbase.int.test or exchange.int.test for urls.

**Comment by nwmartin** [comment]
I'm going to make all of the above changes, but let's not merge this pull request until the HAM-4 package rename task is also complete.

**Comment by nwmartin** [comment]
Don't merge this pull request, but make the above changes for HAM-142.

**Comment by nwmartin** [comment]
This is being closed for the HAM-4 variation.

**Pull request closed without merging**
